--CRIA BANCO
--CREATE DATABASE TESTE_CONSTRAINT;
--GO 
USE TESTE_CONSTRAINT;

--TABELA DE TIPOS (CATEGORIA) DE PRODUTO

CREATE TABLE TB_TIPO_PRODUTO (
	COD_TIPO INT IDENTITY NOT NULL,
	TIPO	 VARCHAR (30)NOT NULL,
	CONSTRAINT PK_TB_TIPO_PRODUTO PRIMARY KEY (COD_TIPO),
	CONSTRAINT UQ_TB_TIPO_PRODUTO_TIPO UNIQUE (TIPO));

	INSERT TB_TIPO_PRODUTO VALUES ('MOUSE')
	INSERT TB_TIPO_PRODUTO VALUES ('PEN-DRIVE')
	INSERT TB_TIPO_PRODUTO VALUES ('HARD DISK')

CREATE TABLE TB_PRODUTO(
	ID_PRODUTO INT IDENTITY NOT NULL,
	DESCRICAO VARCHAR(50),
	COD_TIPO  INT ,
	PRECO_CUSTO		NUMERIC(10,2),
	PRECO_VENDA		NUMERIC (10,2),
	QTD_REAL		NUMERIC(10,2),
	QTD_MINIMA		NUMERIC (10,2),
	DATA_CADASTRO	DATETIME DEFAULT GETDATE(),
	SN_ATIVO		CHAR(1) DEFAULT 'S',
	CONSTRAINT PK_TB_PRODUTO PRIMARY KEY(ID_PRODUTO),
	CONSTRAINT UQ_TB_PRODUTO_DESCRICAO UNIQUE (DESCRICAO),
	CONSTRAINT CK_TB_PRODUTO_PRECOS
			CHECK (PRECO_VENDA >= PRECO_CUSTO),
	CONSTRAINT CK_TB_PRODUTO_DATA_CAD
			CHECK(DATA_CADASTRO<=GETDATE()),
	CONSTRAINT CK_TB_PRODUTO_SN_ATIVO
			CHECK(SN_ATIVO IN ('N','S')),
	CONSTRAINT FK_TB_PRODUTO_TIPO_PRODUTO
			FOREIGN KEY (COD_TIPO)
			REFERENCES TB_TIPO_PRODUTO(COD_TIPO)	
	
	)

INSERT TB_PRODUTO(
	DESCRICAO,
	COD_TIPO,
	PRECO_CUSTO,
	PRECO_VENDA,
	QTD_REAL,QTD_MINIMA)
	VALUES ('TESTANDO INCLUSAO',1,10,12,10,5);

SELECT *
FROM dbo.TB_PRODUTO		

INSERT dbo.TB_PRODUTO (
	DESCRICAO
	,COD_TIPO
	,PRECO_CUSTO
	,PRECO_VENDA
	,QTD_REAL
	,QTD_MINIMA
	)
VALUES (
	'TESTANDO INCLUSAO'
	,10
	,10
	,12
	,10
	,5
	)

INSERT TB_PRODUTO(
	DESCRICAO,
	COD_TIPO,
	PRECO_CUSTO,
	PRECO_VENDA,
	QTD_REAL,
	QTD_MINIMA)
	VALUES ('TESTANDO INCLUSAO 2',10,10,12,10,5);



INSERT TB_PRODUTO(
	DESCRICAO,
	COD_TIPO,
	PRECO_CUSTO,
	PRECO_VENDA,
	QTD_REAL,
	QTD_MINIMA)
	VALUES ('TESTANDO INCLUSAO 2',1,14,12,10,5);



USE TESTE_CONSTRAINT
GO
DROP TABLE TB_PRODUTO
GO
DROP TABLE TB_TIPO_PRODUTO
GO
--CRIAÇÃO DA TABELA TIPO_PRODUTO
CREATE TABLE TB_TIPO_PRODUTO(
	COD_TIPO	INT IDENTITY NOT NULL,
	TIPO		VARCHAR(30 ) NOT NULL
	)
ALTER TABLE TB_TIPO_PRODUTO ADD 
	CONSTRAINT PK_TIPO_PRODUTO PRIMARY KEY (COD_TIPO);
ALTER TABLE TB_TIPO_PRODUTO ADD
	CONSTRAINT UQ_TIPO_PRODUTO_TIPO UNIQUE (TIPO); 

CREATE TABLE TB_PRODUTO (
	ID_PRODUTO	INT IDENTITY NOT NULL,
	DESCRICAO	VARCHAR (50),
	COD_TIPO	INT ,
	PRECO_CUSTO	NUMERIC (10,2),
	PRECO_VENDA NUMERIC(10,2),
	QTD_REAL	NUMERIC(10,2),
	QTD_MINIMA	NUMERIC(10,2),
	DATA_CADASTRO DATETIME ,
	SN_ATIVO	CHAR(1)
	)	

ALTER TABLE TB_PRODUTO ADD
	CONSTRAINT PK_TB_PRODUTO PRIMARY KEY (ID_PRODUTO);
ALTER TABLE TB_PRODUTO ADD
	CONSTRAINT UQ_TB_PRODUTO_DESCRICAO UNIQUE (DESCRICAO);


ALTER TABLE TB_PRODUTO ADD 
	CONSTRAINT CK_TB_PRODUTO_PRECOS
		CHECK(PRECO_VENDA >=PRECO_CUSTO),

	CONSTRAINT CK_TB_PRODUTO_DATA_CAD 
		CHECK (DATA_CADASTRO <=GETDATE()),

	CONSTRAINT CK_TB_PRODUTO_SN_ATIVO
		CHECK (SN_ATIVO IN ('N','S')),

	CONSTRAINT FK_TB_PRODUTO_TIPO_PRODUTO
		FOREIGN KEY (COD_TIPO )
		REFERENCES TB_TIPO_PRODUTO (COD_TIPO ),

	CONSTRAINT DF_TB_PRODUTO_SN_ATIVO DEFAULT ('S') FOR SN_ATIVO,

	CONSTRAINT DF_TB_PRODUTO_DATA_CADASTRO DEFAULT (GETDATE ()) FOR DATA_CADASTRO ; 
