-- INFORMAÇOES SOBRE LOGINS DA INSTACIA SQL
-- CRIANDO LOGIN 

--LOGIN DE WINDOWS 
CREATE LOGIN  [IMPACTA\DBA] FROM WINDOWS 
GO

--LOGIN DE SQL 

CREATE LOGIN DBA_IMPACTA WITH PASSWORD ='5PL1C359@@'
GO
--CRIANDO USUARIOS 

--ADICIONANDO AO SERVER ROLE DBCREATOR

EXEC SP_ADDSRVROLEMEMBER DBA_IMPACTA ,DBCREATOR 

--REMOVENDO DO ROLE SERVER 

EXEC SP_DROPSRVROLEMEMBER DBA_IMPACTA , DBCREATOR

--EXIBIR AS SERVER ROLE 

EXEC SP_HELPSRVROLE


--EXIBINDO AS PERMISSOES DE CADA SERVER ROLE 

EXEC SP_SRVROLEPERMISSION 

-- EXIBINDO OS MEMBROS DAS SERVER ROLE 

EXEC SP_HELPSRVROLEMEMBER

--PARA CONSULTAR AS SERVER ROLES ATRIBUIDAS AOS LOGINS 

SELECT P.NAME ,P.TYPE_DESC,PP.NAME,PP.TYPE_DESC
FROM SYS.SERVER_ROLE_MEMBERS ROLES
JOIN SYS.SERVER_PRINCIPALS  P 
ON ROLES.MEMBER_PRINCIPAL_ID =P.PRINCIPAL_ID 
JOIN SYS.SERVER_PRINCIPALS PP
ON ROLES.ROLE_PRINCIPAL_ID = PP.PRINCIPAL_ID 