-- CONSULTA PARA VER TODAS AS PERMISSOES ATRIBUIDA EM UM BANCO 
SELECT DP.CLASS_DESC,
	   DP.PERMISSION_NAME,
	   DP.STATE_DESC,
	   OBJECTNAME=OBJECT_NAME(MAJOR_ID),
	   GRANTEENAME = GRANTEE.NAME,
	   GRANTORNAME = GRANTOR.NAME
FROM SYS.DATABASE_PERMISSIONS DP
JOIN SYS.DATABASE_PRINCIPALS GRANTEE
ON DP.GRANTEE_PRINCIPAL_ID = GRANTEE.PRINCIPAL_ID
JOIN SYS.DATABASE_PRINCIPALS GRANTOR
ON DP.GRANTOR_PRINCIPAL_ID=GRANTOR.PRINCIPAL_ID