--CONSULTANDO O TAMANHO DE TODOS OS ARQUIVOS DO SERVIDOR 

SELECT 
	D.NAME AS BANCO,
	F.NAME AS TIPO_ARQUIVO,
	F.PHYSICAL_NAME AS ARQUIVO,
	F.STATE_DESC AS STATUS ,
	F.SIZE * 8/1024 AS TAMANHO_MB
FROM SYS.MASTER_FILES F
	INNER JOIN  SYS.DATABASES D ON D.DATABASE_ID =F.DATABASE_ID
ORDER BY 
	D.NAME